Repository AY2122S2-CS2103-W16-1/tp, pull requests merged in 2022-03, with the labels that each got.

#80 Alter GUI
  src/main/java/unibook/ui/cards/PersonCard.java
  src/main/java/unibook/ui/listpanels/PersonListPanel.java
Labels: priority.Medium

#81 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: priority.High, type.Documentation

#85 Fix delete sequence diagram
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: priority.High

#86 Update DG for Add Command Implementation
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: priority.High, type.Documentation

#84 Enhance AddCommand
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/logic/parser/AddCommandParser.java
  src/main/java/unibook/logic/parser/CliSyntax.java
  src/main/java/unibook/logic/parser/ParserUtil.java
  src/main/java/unibook/model/Model.java
  src/main/java/unibook/model/ModelManager.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/module/group/Group.java
  src/main/java/unibook/model/person/Email.java
  src/main/java/unibook/model/person/Phone.java
  src/test/java/unibook/logic/commands/AddCommandTest.java
  src/test/java/unibook/storage/JsonUniBookStorageTest.java
Labels: priority.High

#87 Edit and refactor storage
  src/main/java/unibook/model/UniBook.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedGroupCode.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedPerson.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedProfessor.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedStudent.java
  src/test/java/unibook/storage/JsonAdaptedProfessorTest.java
Labels: priority.High

#89 Major edits to UI to support groups and improve viewing experience
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/logic/commands/ListCommand.java
  src/main/java/unibook/logic/parser/AddCommandParser.java
  src/main/java/unibook/logic/parser/EditCommandParser.java
  src/main/java/unibook/logic/parser/ParserUtil.java
  src/main/java/unibook/model/UniBook.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/module/ModuleKeyEvent.java
  src/main/java/unibook/model/module/group/Group.java
  src/main/java/unibook/model/util/SampleDataUtil.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModule.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModuleKeyEvent.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedPerson.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedProfessor.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedStudent.java
  src/main/java/unibook/ui/MainWindow.java
  src/main/java/unibook/ui/Ui.java
  src/main/java/unibook/ui/UiManager.java
  src/main/java/unibook/ui/cards/GroupCard.java
  src/main/java/unibook/ui/cards/ModuleCard.java
  src/main/java/unibook/ui/cards/ModuleKeyEventCard.java
  src/main/java/unibook/ui/cards/ProfessorCard.java
  src/main/java/unibook/ui/cards/StudentCard.java
  src/main/java/unibook/ui/listpanels/GroupListPanel.java
  src/main/java/unibook/ui/listpanels/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/cards/GroupCard.fxml
  src/main/resources/view/cards/ModuleCard.fxml
  src/main/resources/view/cards/ModuleKeyEventCard.fxml
  src/main/resources/view/cards/PersonListCard.fxml
  src/main/resources/view/cards/ProfessorCard.fxml
  src/main/resources/view/cards/StudentCard.fxml
  src/main/resources/view/cards/StudentListCard.fxml
  src/main/resources/view/listpanels/GroupListPanel.fxml
Labels: priority.High

#92 Add method to retrieve showing groups from ui
  src/main/java/unibook/ui/MainWindow.java
  src/main/java/unibook/ui/Ui.java
  src/main/java/unibook/ui/UiManager.java
  src/main/java/unibook/ui/listpanels/GroupListPanel.java
Labels: priority.High

#94 Fix SampleDataUtil
  src/main/java/unibook/model/util/SampleDataUtil.java
Labels: priority.High

#104 Fix storage flaws
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedGroup.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModule.java
Labels: type.Bug, priority.High

#103 Major UI enhancements
  src/main/java/unibook/commons/core/Messages.java
  src/main/java/unibook/commons/util/TriFunction.java
  src/main/java/unibook/logic/LogicManager.java
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/logic/commands/EditCommand.java
  src/main/java/unibook/logic/commands/ListCommand.java
  src/main/java/unibook/logic/parser/AddCommandParser.java
  src/main/java/unibook/logic/parser/ListCommandParser.java
  src/main/java/unibook/logic/parser/ParserUtil.java
  src/main/java/unibook/model/UniBook.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/module/ModuleKeyEvent.java
  src/main/java/unibook/ui/MainWindow.java
  src/main/java/unibook/ui/UiManager.java
  src/main/java/unibook/ui/cards/GroupCard.java
  src/main/java/unibook/ui/cards/ModuleAndGroupMiniCard.java
  src/main/java/unibook/ui/cards/ModuleCard.java
  src/main/java/unibook/ui/cards/ModuleKeyEventCard.java
  src/main/java/unibook/ui/cards/ProfessorCard.java
  src/main/java/unibook/ui/exceptions/ButtonActionException.java
  src/main/java/unibook/ui/listpanels/GroupListPanel.java
  src/main/java/unibook/ui/listpanels/ModuleListPanel.java
  src/main/java/unibook/ui/listpanels/PersonListPanel.java
  src/main/java/unibook/ui/util/CustomListChangeListeners.java
  src/main/java/unibook/ui/util/CustomPaneListFiller.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/unibook_icon.png
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/cards/GroupCard.fxml
  src/main/resources/view/cards/ModuleAndGroupMiniCard.fxml
  src/main/resources/view/cards/ModuleCard.fxml
  src/main/resources/view/cards/ModuleKeyEventCard.fxml
  src/main/resources/view/cards/ProfessorCard.fxml
  src/main/resources/view/cards/StudentCard.fxml
  src/main/resources/view/listpanels/GroupListPanel.fxml
  src/main/resources/view/listpanels/ModuleListPanel.fxml
  src/main/resources/view/listpanels/PersonListPanel.fxml
  src/test/java/unibook/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.Medium

#101 Add delete command groups
  docs/UserGuide.md
  src/main/java/unibook/commons/core/Messages.java
  src/main/java/unibook/logic/commands/DeleteCommand.java
  src/main/java/unibook/logic/parser/CliSyntax.java
  src/main/java/unibook/logic/parser/DeleteCommandParser.java
  src/main/java/unibook/logic/parser/ParserUtil.java
  src/main/java/unibook/model/Model.java
  src/main/java/unibook/model/ModelManager.java
  src/main/java/unibook/model/UniBook.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/module/ModuleList.java
  src/main/java/unibook/model/module/group/Group.java
  src/main/java/unibook/model/person/Person.java
  src/main/java/unibook/model/person/Professor.java
  src/main/java/unibook/model/person/Student.java
  src/main/java/unibook/model/person/UniquePersonList.java
  src/test/java/unibook/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.High

#106 Update Index and UG
  docs/UserGuide.md
  docs/images/GroupsPage.png
  docs/images/ModulesPage.png
  docs/images/Ui.png
Labels: type.Documentation

#107 Fix status badge links on index.md
  docs/index.md
Labels: type.Documentation

#108 Update UserGuide for Add Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#110 Edit find command and docs
  README.md
  docs/UserGuide.md
  docs/images/GroupsPage.png
  docs/images/ModulesPage.png
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findCommandResult.png
  docs/images/groupsPage.png
  docs/images/helpMessage.png
  docs/images/modulesPage.png
  src/main/java/unibook/logic/commands/FindCommand.java
Labels: priority.High
