Repository AY2122S2-CS2103-W16-1/tp, pull requests merged in 2022-04, with the labels that each got.

#111 Edit error messages for Add Command
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/logic/parser/AddCommandParser.java
  src/main/java/unibook/logic/parser/ParserUtil.java
Labels: priority.High

#125 Fix typos and shift examples around in UG for Add Command
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#161 Fix duplicate module bug
  src/main/java/unibook/model/module/Module.java
Labels: type.Bug, priority.High, bug.FunctionalityBug

#164 Update UG table
  docs/UserGuide.md
Labels: bug.DocumentationBug

#170 Update Add Command to allow persons of the same name to be added
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/model/Model.java
  src/main/java/unibook/model/ModelManager.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/person/UniquePersonList.java
  src/test/java/unibook/logic/commands/AddCommandTest.java
Labels: priority.High, severity.High, bug.FunctionalityBug

#167 Fixed Issue #150
  src/main/java/unibook/logic/commands/DeleteCommand.java
  src/main/java/unibook/logic/parser/DeleteCommandParser.java
Labels: severity.High, bug.FunctionalityBug

#159 Update UG for Edit Command
  docs/UserGuide.md
  src/main/java/unibook/commons/core/Messages.java
  src/main/java/unibook/logic/commands/EditCommand.java
  src/main/java/unibook/logic/parser/EditCommandParser.java
  src/main/java/unibook/logic/parser/ParserUtil.java
  src/main/java/unibook/model/Model.java
  src/main/java/unibook/model/ModelManager.java
  src/main/java/unibook/model/UniBook.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/module/ModuleCode.java
  src/main/java/unibook/model/module/ModuleName.java
  src/main/java/unibook/model/module/group/Group.java
  src/main/java/unibook/model/person/Name.java
  src/main/java/unibook/model/person/UniquePersonList.java
  src/test/java/unibook/logic/commands/AddCommandTest.java
  src/test/java/unibook/logic/parser/EditCommandParserTest.java
  src/test/java/unibook/model/person/UniquePersonListTest.java
Labels: type.Documentation

#172 Branch fix text cutting off
  src/main/java/unibook/model/module/group/Group.java
  src/main/java/unibook/ui/cards/ModuleAndGroupMiniCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/cards/GroupCard.fxml
  src/main/resources/view/cards/ModuleAndGroupMiniCard.fxml
  src/main/resources/view/cards/ModuleCard.fxml
  src/main/resources/view/cards/ModuleKeyEventCard.fxml
  src/main/resources/view/cards/ProfessorCard.fxml
  src/main/resources/view/cards/StudentCard.fxml
Labels: priority.High, bug.FunctionalityBug

#180 Format command
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
Labels: bug.DocumentationBug

#185 Fix link bug in command table
  docs/UserGuide.md
Labels: bug.DocumentationBug

#187 Fix input validation bugs
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/model/module/Module.java
  src/main/java/unibook/model/module/ModuleCode.java
  src/main/java/unibook/model/module/ModuleName.java
  src/main/java/unibook/model/module/group/Group.java
  src/main/java/unibook/model/person/Office.java
  src/main/java/unibook/model/tag/Tag.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedGroup.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModule.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModuleCode.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedModuleKeyEvent.java
  src/main/java/unibook/storage/adaptedmodeltypes/JsonAdaptedStudent.java
Labels: type.Bug, priority.High, bug.FunctionalityBug

#188 Edited GUI section of UG
  docs/UserGuide.md
Labels: type.Documentation

#178 Fix error messages for Add Command
  src/main/java/unibook/logic/commands/AddCommand.java
  src/main/java/unibook/logic/parser/AddCommandParser.java
  src/main/java/unibook/logic/parser/ParserUtil.java
  src/main/java/unibook/model/module/ModuleKeyEvent.java
  src/main/java/unibook/model/person/Office.java
Labels: priority.High, severity.High, bug.FunctionalityBug

#191 Fix small GUI bugs
  src/main/java/unibook/ui/util/CustomPaneListFiller.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainTheme.css
  src/main/resources/view/cards/ModuleCard.fxml
  src/main/resources/view/listpanels/PersonListPanel.fxml
Labels: priority.Medium, bug.FunctionalityBug

#192 Edit GUI section of UG
  docs/UserGuide.md
Labels: type.Documentation

#193 Edit UG
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/groupsPage.png
  docs/images/groupsView.png
  docs/images/modulesPage.png
  docs/images/modulesView.png
  docs/images/peopleView.png
  docs/index.md
  src/main/java/unibook/commons/core/Messages.java
  src/main/java/unibook/model/person/Email.java
Labels: type.Documentation

#195 Fix UG issues
  docs/UserGuide.md
  docs/index.md
Labels: type.Documentation

#196 Branch update ug
  docs/UserGuide.md
Labels: type.Documentation

#201 Fix table not rendering
  docs/UserGuide.md
Labels: type.Documentation

#194 Add group to grouplist if group page is showing
  src/main/java/unibook/logic/commands/AddCommand.java
Labels: priority.High, bug.FunctionalityBug

#204 Edit UG format
  docs/UserGuide.md
Labels: type.Documentation

#205 Update UG for Add Command
  docs/UserGuide.md
Labels: priority.High, bug.DocumentationBug

#208 Add Bens Portfolio
  docs/UserGuide.md
  docs/team/benmurphyy.md
Labels: type.Documentation

#210 Ryan's PPP, Delete command DG, use case, user story
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/team/ryanwalterlee.md
Labels: type.Documentation

#217 Branch update dg
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiViewsDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiViewsDiagram.png
Labels: type.Documentation

#218 Branch update DG for add
  docs/DeveloperGuide.md
Labels: priority.High

#220 Update Yoke's PPP
  docs/AboutUs.md
  docs/team/yokester98.md
Labels: priority.High

#221 Branch update yokes ppp
  docs/team/yokester98.md
Labels: priority.High

#222 Fix PPP links
  docs/DeveloperGuide.md
  docs/team/ryanwalterlee.md
Labels: type.Documentation

#224 Manual Testing, fix minor delete tag error message, remove todo and prints
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/unibook/model/person/Person.java
  src/test/java/unibook/logic/commands/DeleteCommandTest.java
  src/test/java/unibook/storage/JsonUniBookStorageTest.java
Labels: type.Documentation

#230 edit typo in dg
  docs/DeveloperGuide.md
Labels: bug.DocumentationBug
